# Generated by Django 4.1.5 on 2023-01-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="rating",
            new_name="ratings",
        ),
    ]
