# Generated by Django 4.1.5 on 2023-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_rename_rating_listing_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
